"""
SQLAlchemy ORM models for the orchestration dashboard.
"""

from datetime import datetime
import json
from database import db


class Run(db.Model):
    """
    Represents a single agent run/execution.
    Tracks the overall result of spawning and executing an agent.
    """
    __tablename__ = "runs"
    
    id = db.Column(db.Integer, primary_key=True)
    agent_name = db.Column(db.String(255), nullable=False)
    agent_type = db.Column(db.String(255), nullable=False)  # 'google_ads', 'crypto', etc.
    status = db.Column(db.String(50), nullable=False)  # 'pending', 'running', 'completed', 'failed'
    result = db.Column(db.JSON, nullable=True)  # Structured result data
    error = db.Column(db.Text, nullable=True)  # Error message if failed
    started_at = db.Column(db.DateTime, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime, nullable=True)
    
    # Relationships
    proposals = db.relationship("Proposal", back_populates="run", cascade="all, delete-orphan")
    executions = db.relationship("Execution", back_populates="run", cascade="all, delete-orphan")
    audit_logs = db.relationship("AuditLog", back_populates="run", cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Run {self.id}: {self.agent_name} ({self.status})>"
    
    def to_dict(self):
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "agent_name": self.agent_name,
            "agent_type": self.agent_type,
            "status": self.status,
            "result": self.result,
            "error": self.error,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
        }


class Proposal(db.Model):
    """
    Represents a proposed action (change) generated by an agent.
    E.g., "increase campaign budget", "execute trade", etc.
    Requires approval/rejection before execution.
    """
    __tablename__ = "proposals"
    
    id = db.Column(db.Integer, primary_key=True)
    run_id = db.Column(db.Integer, db.ForeignKey("runs.id"), nullable=False)
    agent_name = db.Column(db.String(255), nullable=False)
    proposal_type = db.Column(db.String(255), nullable=False)  # 'campaign_adjustment', 'trade', etc.
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text, nullable=False)
    proposed_data = db.Column(db.JSON, nullable=False)  # The detailed proposal payload
    approval_status = db.Column(db.String(50), nullable=False)  # 'pending', 'approved', 'rejected'
    approved_by = db.Column(db.String(255), nullable=True)  # User who approved/rejected
    approved_at = db.Column(db.DateTime, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Relationship
    run = db.relationship("Run", back_populates="proposals")
    execution = db.relationship("Execution", back_populates="proposal", uselist=False, cascade="all, delete-orphan")
    
    def __repr__(self):
        return f"<Proposal {self.id}: {self.proposal_type} ({self.approval_status})>"
    
    def to_dict(self):
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "run_id": self.run_id,
            "agent_name": self.agent_name,
            "proposal_type": self.proposal_type,
            "title": self.title,
            "description": self.description,
            "proposed_data": self.proposed_data,
            "approval_status": self.approval_status,
            "approved_by": self.approved_by,
            "approved_at": self.approved_at.isoformat() if self.approved_at else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class Execution(db.Model):
    """
    Represents the execution of an approved proposal.
    Tracks the result and any side effects of running the proposed action.
    """
    __tablename__ = "executions"
    
    id = db.Column(db.Integer, primary_key=True)
    run_id = db.Column(db.Integer, db.ForeignKey("runs.id"), nullable=False)
    proposal_id = db.Column(db.Integer, db.ForeignKey("proposals.id"), nullable=False)
    status = db.Column(db.String(50), nullable=False)  # 'pending', 'executing', 'completed', 'failed', 'rolled_back'
    result = db.Column(db.JSON, nullable=True)  # Result of the execution
    error = db.Column(db.Text, nullable=True)  # Error message if failed
    rollback_data = db.Column(db.JSON, nullable=True)  # Data needed to undo this execution
    started_at = db.Column(db.DateTime, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime, nullable=True)
    
    # Relationships
    run = db.relationship("Run", back_populates="executions")
    proposal = db.relationship("Proposal", back_populates="execution")
    
    def __repr__(self):
        return f"<Execution {self.id}: proposal {self.proposal_id} ({self.status})>"
    
    def to_dict(self):
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "run_id": self.run_id,
            "proposal_id": self.proposal_id,
            "status": self.status,
            "result": self.result,
            "error": self.error,
            "rollback_data": self.rollback_data,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
        }


class AuditLog(db.Model):
    """
    Comprehensive audit log for all system actions.
    Used for compliance, debugging, and security auditing.
    """
    __tablename__ = "audit_logs"
    
    id = db.Column(db.Integer, primary_key=True)
    run_id = db.Column(db.Integer, db.ForeignKey("runs.id"), nullable=True)
    action = db.Column(db.String(255), nullable=False)  # 'run_started', 'proposal_approved', 'execution_completed', etc.
    agent_name = db.Column(db.String(255), nullable=False)
    actor = db.Column(db.String(255), nullable=True)  # User who triggered action, if any
    details = db.Column(db.JSON, nullable=False)  # Arbitrary structured details
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    
    # Relationship
    run = db.relationship("Run", back_populates="audit_logs")
    
    def __repr__(self):
        return f"<AuditLog {self.id}: {self.action}>"
    
    def to_dict(self):
        """Convert to dictionary for API responses."""
        return {
            "id": self.id,
            "run_id": self.run_id,
            "action": self.action,
            "agent_name": self.agent_name,
            "actor": self.actor,
            "details": self.details,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
